/*The Fibonacci Series is a mathematical series that starts with 0 and 1 and is generated by adding the two preceding numbers to generate the next one

Denoted by Fn

Fn = 0 1 1 2 3 5 8 13 21*/

#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

int main() {
    int p,q,r,n,i;
    scanf("%d",&n);
    
    p=0;
    q=1;
    for(i=1;i<=n;i++)
    {
        printf("%d\t",p);
        r=p+q;
        p=q;
        q=r;
    }
        

     
    return 0;
}
